DELETE FROM AlbumArtist;
DELETE FROM AlbumGenre;
DELETE FROM AlbumSong;
DELETE FROM SongArtist;
DELETE FROM Album;
DELETE FROM Artist;
DELETE FROM Song;

DROP TABLE IF EXISTS AlbumArtist;
DROP TABLE IF EXISTS AlbumGenre;
DROP TABLE IF EXISTS AlbumSong;
DROP TABLE IF EXISTS SongArtist;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Song;

CREATE TABLE Genre (
	GenreId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL
);

--SELECT * FROM Genre;

CREATE TABLE Artist (
	ArtistId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL
);

--SELECT * FROM Artist;

CREATE TABLE Song (
	SongId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL
);

--SELECT * FROM Song;

CREATE TABLE Album (
	AlbumId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL
);

--SELECT * FROM Album;

CREATE TABLE AlbumGenre (
	AlbumGenreId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	GenreId INTEGER NOT NULL,
	AlbumId INTEGER NOT NULL,
	FOREIGN KEY (GenreId) REFERENCES Genre(GenreId),
	FOREIGN KEY (AlbumId) REFERENCES Album(AlbumId)
);

--SELECT * FROM AlbumGenre;

CREATE TABLE AlbumArtist (
	AlbumArtistId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ArtistId INTEGER NOT NULL,
	AlbumId INTEGER NOT NULL,
	FOREIGN KEY (ArtistId) REFERENCES Artist(ArtistId),
	FOREIGN KEY (AlbumId) REFERENCES Album(AlbumId)
);

--SELECT * FROM AlbumArtist;

CREATE TABLE AlbumSong (
	AlbumSongId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SongId INTEGER NOT NULL,
	AlbumId INTEGER NOT NULL,
	Featured INTEGER NOT NULL,
	FOREIGN KEY (SongId) REFERENCES Song(SongId),
	FOREIGN KEY (AlbumId) REFERENCES Album(AlbumId)
);

--SELECT * FROM AlbumGenre;

CREATE TABLE SongArtist (
	SongArtistId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ArtistId INTEGER NOT NULL,
	SongId INTEGER NOT NULL,
	Featured INTEGER NOT NULL,
	FOREIGN KEY (ArtistId) REFERENCES Artist(ArtistId),
	FOREIGN KEY (SongId) REFERENCES Song(SongId)
);

--SELECT * FROM SongArtist;

