# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_hockeyplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockeyteam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
